export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const NET_CHECK_START = 'NET_CHECK_START';
export const NET_CHECK_SUCCESS = 'NET_CHECK_SUCCESS';
export const NET_CHECK_FAIL = 'NET_CHECK_FAIL';

export const GET_BALANCE_START = 'GET_BALANCE_START';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL';

export const GET_DIGEST_START = 'GET_DIGEST_START';
export const GET_DIGEST_SUCCESS = 'GET_DIGEST_SUCCESS';
export const GET_DIGEST_FAIL = 'GET_DIGEST_FAIL';

export const GET_APP_SETTINGS_START = 'GET_APP_SETTINGS_START';
export const GET_APP_SETTINGS_SUCCESS = 'GET_APP_SETTINGS_SUCCESS';
export const GET_APP_SETTINGS_FAIL = 'GET_APP_SETTINGS_FAIL';
export const GET_USER_DATA_START = 'GET_USER_DATA_START';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';

export const CREATE_NEW_FOLDER_START = 'CREATE_NEW_FOLDER_START';
export const CREATE_NEW_FOLDER_SUCCESS = 'CREATE_NEW_FOLDER_SUCCESS';
export const CREATE_NEW_FOLDER_FAIL = 'CREATE_NEW_FOLDER_FAIL';
export const EDIT_FOLDER_START = 'EDIT_FOLDER_START';
export const EDIT_FOLDER_SUCCESS = 'EDIT_FOLDER_SUCCESS';
export const EDIT_FOLDER_FAIL = 'EDIT_FOLDER_FAIL';
export const DELETE_FOLDER_START = 'DELETE_FOLDER_START';
export const DELETE_FOLDER_SUCCESS = 'DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_FAIL = 'DELETE_FOLDER_FAIL';

export const UPLOAD_FILES_START = 'UPLOAD_FILES_START';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const UPLOAD_FILES_FAIL = 'UPLOAD_FILES_FAIL';
export const DOWNLOAD_FILE_START = 'DOWNLOAD_FILE_START';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAIL = 'DOWNLOAD_FILE_FAIL';
export const SAVE_DOWNLOADED_FILE = 'SAVE_DOWNLOADED_FILE';
export const REMOVE_FILE_START = 'REMOVE_FILE_START';
export const REMOVE_FILE_SUCCESS = 'REMOVE_FILE_SUCCESS';
export const REMOVE_FILE_FAIL = 'REMOVE_FILE_FAIL';

export const CREATE_NOTE_START = 'CREATE_NOTE_START';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_FAIL = 'CREATE_NOTE_FAIL';
export const EDIT_NOTE_START = 'EDIT_NOTE_START';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_FAIL = 'EDIT_NOTE_FAIL';
export const REMOVE_NOTE_START = 'REMOVE_NOTE_START';
export const REMOVE_NOTE_SUCCESS = 'REMOVE_NOTE_SUCCESS';
export const REMOVE_NOTE_FAIL = 'REMOVE_NOTE_FAIL';
