//  auth actions
export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const REGISTRATION_CLEAN_UP = 'REGISTRATION_CLEAN_UP';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

//  common actions
export const NET_CHECK_START = 'NET_CHECK_START';
export const NET_CHECK_SUCCESS = 'NET_CHECK_SUCCESS';
export const NET_CHECK_FAIL = 'NET_CHECK_FAIL';

//  blockchain actions
export const GET_BALANCE_START = 'GET_BALANCE_START';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL';

//  settings ?
// export const GET_APP_SETTINGS_START = 'GET_APP_SETTINGS_START';
// export const GET_APP_SETTINGS_SUCCESS = 'GET_APP_SETTINGS_SUCCESS';
// export const GET_APP_SETTINGS_FAIL = 'GET_APP_SETTINGS_FAIL';

//  folders CRUD
export const CREATE_NEW_FOLDER_START = 'CREATE_NEW_FOLDER_START';
export const CREATE_NEW_FOLDER_SUCCESS = 'CREATE_NEW_FOLDER_SUCCESS';
export const CREATE_NEW_FOLDER_FAIL = 'CREATE_NEW_FOLDER_FAIL';

export const EDIT_FOLDER_START = 'EDIT_FOLDER_START';
export const EDIT_FOLDER_SUCCESS = 'EDIT_FOLDER_SUCCESS';
export const EDIT_FOLDER_FAIL = 'EDIT_FOLDER_FAIL';

export const REMOVE_FOLDERS_START = 'REMOVE_FOLDERS_START';
export const REMOVE_FOLDERS_SUCCESS = 'REMOVE_FOLDERS_SUCCESS';
export const REMOVE_FOLDERS_FAIL = 'REMOVE_FOLDERS_FAIL';

//  files CRUD
export const UPLOAD_FILES_START = 'UPLOAD_FILES_START';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const UPLOAD_FILES_FAIL = 'UPLOAD_FILES_FAIL';

export const DOWNLOAD_FILE_START = 'DOWNLOAD_FILE_START';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAIL = 'DOWNLOAD_FILE_FAIL';

export const REMOVE_FILES_START = 'REMOVE_FILES_START';
export const REMOVE_FILES_SUCCESS = 'REMOVE_FILES_SUCCESS';
export const REMOVE_FILES_FAIL = 'REMOVE_FILES_FAIL';

//  notes CRUD
export const CREATE_NOTE_START = 'CREATE_NOTE_START';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_FAIL = 'CREATE_NOTE_FAIL';

export const EDIT_NOTE_START = 'EDIT_NOTE_START';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_FAIL = 'EDIT_NOTE_FAIL';

export const REMOVE_NOTES_START = 'REMOVE_NOTE_START';
export const REMOVE_NOTES_SUCCESS = 'REMOVE_NOTE_SUCCESS';
export const REMOVE_NOTES_FAIL = 'REMOVE_NOTE_FAIL';

//  ghost time
export const SET_GHOST_TIME_START = 'SET_GHOST_TIME_START';
export const SET_GHOST_TIME_SUCCESS = 'SET_GHOST_TIME_SUCCESS';
export const SET_GHOST_TIME_FAIL = 'SET_GHOST_TIME_FAIL';

export const SET_SEARCH_WORD = 'SET_SEARCH_WORD';
